from __future__ import annotations

import argparse
import re
import secrets
from dataclasses import dataclass
from typing import Any, Dict, List, Tuple

import psycopg2
import requests
from psycopg2.extras import Json, execute_values
from supabase import create_client

PK_RE = re.compile(r"<pk/>")
FK_RE = re.compile(r"<fk table='([^']+)' column='([^']+)'/>")


@dataclass
class ColumnDef:
    name: str
    pg_type: str
    not_null: bool
    default_sql: str | None
    is_pk: bool
    fk_ref: Tuple[str, str] | None


def qident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def map_pg_type(meta: Dict[str, Any]) -> str:
    fmt = (meta.get("format") or "").strip()
    typ = (meta.get("type") or "").strip()

    if fmt.startswith("public.vector(") and fmt.endswith(")"):
        return fmt.replace("public.", "", 1)

    mapping = {
        "bigint": "bigint",
        "integer": "integer",
        "double precision": "double precision",
        "numeric": "numeric",
        "uuid": "uuid",
        "text": "text",
        "date": "date",
        "timestamp with time zone": "timestamptz",
        "timestamp without time zone": "timestamp",
        "jsonb": "jsonb",
        "boolean": "boolean",
    }
    if fmt in mapping:
        return mapping[fmt]

    if typ == "integer":
        return "integer"
    if typ == "number":
        return "numeric"
    if typ == "boolean":
        return "boolean"
    return "text"


def map_default(meta: Dict[str, Any], pg_type: str) -> str | None:
    if "default" not in meta:
        return None

    d = meta.get("default")
    if d is None:
        return None
    if isinstance(d, bool):
        return "true" if d else "false"
    if isinstance(d, (int, float)):
        return str(d)

    s = str(d).strip()
    if not s:
        return None

    s_lower = s.lower()
    if s_lower in {"true", "false"}:
        return s_lower
    if re.fullmatch(r"-?\d+(\.\d+)?", s):
        return s

    # 已知 SQL 表达式保持原样。
    if s_lower in {
        "now()",
        "timezone('utc'::text, now())",
        "gen_random_uuid()",
    }:
        return s

    # 兜底按字符串字面量处理。
    escaped = s.replace("'", "''")
    return f"'{escaped}'"


def parse_openapi_tables(openapi: Dict[str, Any]) -> Dict[str, List[ColumnDef]]:
    definitions = openapi.get("definitions", {})
    tables: Dict[str, List[ColumnDef]] = {}

    for table, d in definitions.items():
        props = d.get("properties", {})
        required = set(d.get("required", []))

        cols: List[ColumnDef] = []
        for col_name, meta in props.items():
            desc = meta.get("description") or ""
            is_pk = bool(PK_RE.search(desc))

            fk_ref = None
            m = FK_RE.search(desc)
            if m:
                fk_ref = (m.group(1), m.group(2))

            pg_type = map_pg_type(meta)
            default_sql = map_default(meta, pg_type)
            not_null = col_name in required or is_pk

            cols.append(
                ColumnDef(
                    name=col_name,
                    pg_type=pg_type,
                    not_null=not_null,
                    default_sql=default_sql,
                    is_pk=is_pk,
                    fk_ref=fk_ref,
                )
            )

        if cols:
            tables[table] = cols

    return tables


def _should_identity(col: ColumnDef) -> bool:
    return (
        col.is_pk
        and col.name == "id"
        and col.pg_type in {"integer", "bigint"}
        and col.default_sql is None
    )


def create_public_tables(conn: Any, tables: Dict[str, List[ColumnDef]], reset_public: bool) -> None:
    with conn.cursor() as cur:
        cur.execute("create extension if not exists vector;")
        cur.execute("create extension if not exists pgcrypto;")

        if reset_public:
            # 仅删除已知远端业务表，保留扩展/系统对象。
            for table in tables.keys():
                cur.execute(f"drop table if exists public.{qident(table)} cascade;")

        for table, cols in tables.items():
            col_sql_parts = []
            for c in cols:
                line = f"{qident(c.name)} {c.pg_type}"
                if _should_identity(c):
                    # 数值主键 `id` 列尽量与托管 Supabase 的行为保持一致。
                    line += " generated by default as identity"
                elif c.default_sql is not None:
                    line += f" default {c.default_sql}"
                if c.not_null:
                    line += " not null"
                col_sql_parts.append(line)

            ddl = f"create table if not exists public.{qident(table)} (" + ", ".join(col_sql_parts) + ");"
            cur.execute(ddl)

        # 若可行则补充主键约束。
        for table, cols in tables.items():
            pk_cols = [c.name for c in cols if c.is_pk]
            if not pk_cols:
                continue
            c_name = f"{table}_pkey"
            cols_sql = ", ".join(qident(x) for x in pk_cols)
            try:
                cur.execute(
                    f"alter table public.{qident(table)} add constraint {qident(c_name)} primary key ({cols_sql});"
                )
            except Exception:
                conn.rollback()
                with conn.cursor() as cur2:
                    # 若约束已存在或后续出现数据冲突，则忽略。
                    cur2.execute("select 1;")
                conn.commit()

    conn.commit()


def sync_table_id_sequence(conn: Any, table: str, cols: List[ColumnDef]) -> None:
    """
    When rows are inserted with explicit IDs, the backing sequence may lag behind.
    Align it to MAX(id)+1 to prevent future insert collisions.
    """
    has_numeric_id = any(c.name == "id" and c.pg_type in {"integer", "bigint"} for c in cols)
    if not has_numeric_id:
        return

    with conn.cursor() as cur:
        cur.execute("select pg_get_serial_sequence(%s, %s);", (f"public.{table}", "id"))
        seq_row = cur.fetchone()
        seq_name = seq_row[0] if seq_row else None
        if not seq_name:
            return

        cur.execute(f"select coalesce(max({qident('id')}), 0) from public.{qident(table)};")
        max_id_row = cur.fetchone()
        max_id = int(max_id_row[0] or 0)
        cur.execute("select setval(%s::regclass, %s, false);", (seq_name, max_id + 1))
    conn.commit()


def fetch_openapi(remote_url: str, service_role_key: str) -> Dict[str, Any]:
    headers = {
        "apikey": service_role_key,
        "Authorization": f"Bearer {service_role_key}",
        "Accept": "application/openapi+json",
    }
    r = requests.get(f"{remote_url.rstrip('/')}/rest/v1/", headers=headers, timeout=60)
    r.raise_for_status()
    return r.json()


def convert_value(value: Any, pg_type: str) -> Any:
    if value is None:
        return None
    if pg_type == "jsonb":
        return Json(value)
    if pg_type.startswith("vector"):
        if isinstance(value, list):
            return "[" + ",".join(str(x) for x in value) + "]"
        return value
    return value


def migrate_public_data(
    remote_url: str,
    remote_service_role_key: str,
    local_db_url: str,
    reset_public: bool,
) -> Tuple[int, int]:
    openapi = fetch_openapi(remote_url, remote_service_role_key)
    tables = parse_openapi_tables(openapi)

    conn = psycopg2.connect(local_db_url)
    conn.autocommit = False
    create_public_tables(conn, tables, reset_public=reset_public)

    remote = create_client(remote_url, remote_service_role_key)

    table_count = 0
    row_count = 0

    for table, cols in tables.items():
        col_names = [c.name for c in cols]
        col_types = {c.name: c.pg_type for c in cols}
        table_count += 1

        with conn.cursor() as cur:
            cur.execute(f"truncate table public.{qident(table)};")
        conn.commit()

        offset = 0
        batch_size = 1000

        while True:
            resp = remote.table(table).select("*").range(offset, offset + batch_size - 1).execute()
            rows = resp.data or []
            if not rows:
                break

            values = []
            for row in rows:
                values.append(
                    tuple(convert_value(row.get(cn), col_types[cn]) for cn in col_names)
                )

            insert_sql = (
                f"insert into public.{qident(table)} ("
                + ", ".join(qident(cn) for cn in col_names)
                + ") values %s"
            )

            with conn.cursor() as cur:
                execute_values(cur, insert_sql, values, page_size=200)
            conn.commit()

            row_count += len(rows)
            if len(rows) < batch_size:
                break
            offset += batch_size

        sync_table_id_sequence(conn, table, cols)

    conn.close()
    return table_count, row_count


def list_all_users(sb_client: Any, per_page: int = 100) -> List[Any]:
    users: List[Any] = []
    page = 1
    while True:
        batch = sb_client.auth.admin.list_users(page=page, per_page=per_page) or []
        users.extend(batch)
        if len(batch) < per_page:
            break
        page += 1
    return users


def migrate_auth_users(
    remote_url: str,
    remote_service_role_key: str,
    local_url: str,
    local_service_role_key: str,
) -> Tuple[int, int, int]:
    remote = create_client(remote_url, remote_service_role_key)
    local = create_client(local_url, local_service_role_key)

    remote_users = list_all_users(remote)
    local_users = list_all_users(local)
    local_user_ids = {u.id for u in local_users}

    created = 0
    skipped = 0
    failed = 0

    for u in remote_users:
        if u.id in local_user_ids:
            skipped += 1
            continue

        email = getattr(u, "email", None) or None
        phone = getattr(u, "phone", None) or None

        # GoTrue 至少需要 email 或 phone 之一。
        if not email and not phone:
            skipped += 1
            continue

        payload: Dict[str, Any] = {
            "id": u.id,
            "password": "Temp#" + secrets.token_hex(8),
            "email_confirm": bool(getattr(u, "email_confirmed_at", None) or getattr(u, "confirmed_at", None)),
            "phone_confirm": bool(getattr(u, "phone_confirmed_at", None)),
            "user_metadata": getattr(u, "user_metadata", {}) or {},
            "app_metadata": getattr(u, "app_metadata", {}) or {},
        }
        if email:
            payload["email"] = email
        if phone:
            payload["phone"] = phone

        try:
            local.auth.admin.create_user(payload)
            created += 1
        except Exception:
            failed += 1

    return len(remote_users), created, skipped + failed


def main() -> int:
    parser = argparse.ArgumentParser(description="Fallback migration: copy public schema/data and auth users via Supabase API.")
    parser.add_argument("--remote-url", required=True)
    parser.add_argument("--remote-service-role-key", required=True)
    parser.add_argument("--local-url", default="http://127.0.0.1:54321")
    parser.add_argument(
        "--local-service-role-key",
        default=(
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
            "eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0."
            "EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
        ),
    )
    parser.add_argument(
        "--local-db-url",
        default="postgresql://postgres:postgres@127.0.0.1:54322/postgres",
    )
    parser.add_argument("--no-reset-public", action="store_true")
    parser.add_argument("--skip-auth-users", action="store_true")
    args = parser.parse_args()

    try:
        t_count, r_count = migrate_public_data(
            remote_url=args.remote_url,
            remote_service_role_key=args.remote_service_role_key,
            local_db_url=args.local_db_url,
            reset_public=not args.no_reset_public,
        )
        print(f"[OK] public tables migrated: {t_count}")
        print(f"[OK] public rows migrated: {r_count}")
    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] public data migration failed: {exc}")
        return 1

    if not args.skip_auth_users:
        try:
            total, created, skipped = migrate_auth_users(
                remote_url=args.remote_url,
                remote_service_role_key=args.remote_service_role_key,
                local_url=args.local_url,
                local_service_role_key=args.local_service_role_key,
            )
            print(f"[OK] remote auth users: {total}")
            print(f"[OK] local auth users created: {created}")
            print(f"[OK] auth users skipped/failed: {skipped}")
        except Exception as exc:  # noqa: BLE001
            print(f"[WARN] auth user migration failed: {exc}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
